export const PAGE_NOT_FOUND = 'PAGE_NOT_FOUND'

export const FETCH_CITIES_REQUEST = 'FETCH_CITIES_REQUEST'
export const FETCH_CITIES_SUCCESS = 'FETCH_CITIES_SUCCESS'
export const FETCH_CITIES_FAIL = 'FETCH_CITIES_FAIL'

export const GET_CITY_REQUEST = 'GET_CITY_REQUEST'
export const GET_CITY_SUCCESS = 'GET_CITY_SUCCESS'
export const GET_CITY_FAIL = 'GET_CITY_FAIL'

export const SMS_LOGIN_REQUEST = 'SMS_LOGIN_REQUEST'
export const SMS_LOGIN_SUCCESS = 'SMS_LOGIN_SUCCESS'
export const SMS_LOGIN_FAIL = 'SMS_LOGIN_FAIL'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const FETCH_ARTICLES_REQUEST = 'FETCH_ARTICLES_REQUEST'
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS'
export const FETCH_ARTICLES_FAIL = 'FETCH_ARTICLES_FAIL'

export const GET_ARTICLE_REQUEST = 'GET_ARTICLE_REQUEST'
export const GET_ARTICLE_SUCCESS = 'GET_ARTICLE_SUCCESS'
export const GET_ARTICLE_FAIL = 'GET_ARTICLE_FAIL'

export const FETCH_BANNERS_REQUEST = 'FETCH_BANNERS_REQUEST'
export const FETCH_BANNERS_SUCCESS = 'FETCH_BANNERS_SUCCESS'
export const FETCH_BANNERS_FAIL = 'FETCH_BANNERS_FAIL'

export const FETCH_PIZZERIAS_REQUEST = 'FETCH_PIZZERIAS_REQUEST'
export const FETCH_PIZZERIAS_SUCCESS = 'FETCH_PIZZERIAS_SUCCESS'
export const FETCH_PIZZERIAS_FAIL = 'FETCH_PIZZERIAS_FAIL'
