export const FETCH_CITIES_REQUEST = 'FETCH_CITIES_REQUEST'
export const FETCH_CITIES_SUCCESS = 'FETCH_CITIES_SUCCESS'
export const FETCH_CITIES_FAIL = 'FETCH_CITIES_FAIL'

export const GET_CITY_REQUEST = 'GET_CITY_REQUEST'
export const GET_CITY_SUCCESS = 'GET_CITY_SUCCESS'
export const GET_CITY_FAIL = 'GET_CITY_FAIL'

export const SMS_LOGIN_REQUEST = 'SMS_LOGIN_REQUEST'
export const SMS_LOGIN_SUCCESS = 'SMS_LOGIN_SUCCESS'
export const SMS_LOGIN_FAIL = 'SMS_LOGIN_FAIL'
